"""Shop catalog: machines you might actually own, and what they physically cannot do."""

from __future__ import annotations

from typing import Any

# Strength numbers are conservative *printed* / *as-manufactured* values, not
# datasheet injection-molded coupons. Units: MPa, g/cm^3, °C, mm.

MATERIALS: dict[str, dict[str, Any]] = {
    "pla": {
        "id": "pla",
        "name": "PLA",
        "process_kinds": ["fdm"],
        "density_g_cm3": 1.24,
        "tensile_xy_mpa": 35.0,
        "tensile_z_mpa": 18.0,
        "flex_modulus_gpa": 2.8,
        "elongation_pct": 6.0,
        "service_temp_c": 50.0,
        "extrude_c": (190, 220),
        "bed_c": 60,
        "needs_enclosure": False,
        "needs_hardened_nozzle": False,
        "notes": "Stiff and easy. Creep and heat are the usual failure modes.",
    },
    "petg": {
        "id": "petg",
        "name": "PETG",
        "process_kinds": ["fdm"],
        "density_g_cm3": 1.27,
        "tensile_xy_mpa": 40.0,
        "tensile_z_mpa": 28.0,
        "flex_modulus_gpa": 2.1,
        "elongation_pct": 20.0,
        "service_temp_c": 70.0,
        "extrude_c": (230, 250),
        "bed_c": 80,
        "needs_enclosure": False,
        "needs_hardened_nozzle": False,
        "notes": "Better layer adhesion and toughness than PLA. First choice for load-bearing FDM brackets.",
    },
    "abs": {
        "id": "abs",
        "name": "ABS",
        "process_kinds": ["fdm"],
        "density_g_cm3": 1.04,
        "tensile_xy_mpa": 33.0,
        "tensile_z_mpa": 22.0,
        "flex_modulus_gpa": 2.0,
        "elongation_pct": 10.0,
        "service_temp_c": 85.0,
        "extrude_c": (230, 250),
        "bed_c": 100,
        "needs_enclosure": True,
        "needs_hardened_nozzle": False,
        "notes": "Warps without an enclosure. Use when PLA/PETG will heat-soften.",
    },
    "asa": {
        "id": "asa",
        "name": "ASA",
        "process_kinds": ["fdm"],
        "density_g_cm3": 1.07,
        "tensile_xy_mpa": 35.0,
        "tensile_z_mpa": 24.0,
        "flex_modulus_gpa": 2.0,
        "elongation_pct": 15.0,
        "service_temp_c": 90.0,
        "extrude_c": (240, 260),
        "bed_c": 100,
        "needs_enclosure": True,
        "needs_hardened_nozzle": False,
        "notes": "Outdoor/UV cousin of ABS.",
    },
    "nylon": {
        "id": "nylon",
        "name": "Nylon (PA6/PA12)",
        "process_kinds": ["fdm"],
        "density_g_cm3": 1.08,
        "tensile_xy_mpa": 50.0,
        "tensile_z_mpa": 30.0,
        "flex_modulus_gpa": 1.5,
        "elongation_pct": 40.0,
        "service_temp_c": 90.0,
        "extrude_c": (250, 280),
        "bed_c": 80,
        "needs_enclosure": True,
        "needs_hardened_nozzle": False,
        "notes": "Tough and hygroscopic. Dry it. Great for clips and living hinges.",
    },
    "pc": {
        "id": "pc",
        "name": "Polycarbonate",
        "process_kinds": ["fdm"],
        "density_g_cm3": 1.20,
        "tensile_xy_mpa": 55.0,
        "tensile_z_mpa": 32.0,
        "flex_modulus_gpa": 2.2,
        "elongation_pct": 12.0,
        "service_temp_c": 110.0,
        "extrude_c": (270, 310),
        "bed_c": 110,
        "needs_enclosure": True,
        "needs_hardened_nozzle": False,
        "notes": "Needs a hot chamber and a hotend that can actually reach PC temps.",
    },
    "tpu": {
        "id": "tpu",
        "name": "TPU (95A)",
        "process_kinds": ["fdm"],
        "density_g_cm3": 1.21,
        "tensile_xy_mpa": 25.0,
        "tensile_z_mpa": 12.0,
        "flex_modulus_gpa": 0.08,
        "elongation_pct": 400.0,
        "service_temp_c": 60.0,
        "extrude_c": (220, 240),
        "bed_c": 40,
        "needs_enclosure": False,
        "needs_hardened_nozzle": False,
        "notes": "Flexible. Do not use for rigid structural brackets.",
    },
    "petg_cf": {
        "id": "petg_cf",
        "name": "PETG-CF",
        "process_kinds": ["fdm"],
        "density_g_cm3": 1.30,
        "tensile_xy_mpa": 48.0,
        "tensile_z_mpa": 26.0,
        "flex_modulus_gpa": 4.5,
        "elongation_pct": 4.0,
        "service_temp_c": 75.0,
        "extrude_c": (240, 260),
        "bed_c": 80,
        "needs_enclosure": False,
        "needs_hardened_nozzle": True,
        "notes": "Stiffer than PETG. Abrasive — hardened nozzle required. More brittle.",
    },
    "pa_cf": {
        "id": "pa_cf",
        "name": "Nylon-CF",
        "process_kinds": ["fdm"],
        "density_g_cm3": 1.15,
        "tensile_xy_mpa": 70.0,
        "tensile_z_mpa": 28.0,
        "flex_modulus_gpa": 6.0,
        "elongation_pct": 5.0,
        "service_temp_c": 100.0,
        "extrude_c": (270, 300),
        "bed_c": 80,
        "needs_enclosure": True,
        "needs_hardened_nozzle": True,
        "notes": "Engineering FDM. Dry filament, abrasive, worth it for high stiffness.",
    },
    "sla_standard": {
        "id": "sla_standard",
        "name": "SLA standard resin",
        "process_kinds": ["sla"],
        "density_g_cm3": 1.18,
        "tensile_xy_mpa": 40.0,
        "tensile_z_mpa": 38.0,
        "flex_modulus_gpa": 2.2,
        "elongation_pct": 8.0,
        "service_temp_c": 50.0,
        "notes": "Isotropic-ish after cure. Brittle compared to PETG. Fine detail.",
    },
    "sla_tough": {
        "id": "sla_tough",
        "name": "SLA tough/engineering resin",
        "process_kinds": ["sla"],
        "density_g_cm3": 1.15,
        "tensile_xy_mpa": 55.0,
        "tensile_z_mpa": 52.0,
        "flex_modulus_gpa": 2.0,
        "elongation_pct": 30.0,
        "service_temp_c": 60.0,
        "notes": "Use this, not standard resin, if the part sees real load.",
    },
    "316l": {
        "id": "316l",
        "name": "316L stainless (DMLS/SLM)",
        "process_kinds": ["metal_am"],
        "density_g_cm3": 7.90,
        "tensile_xy_mpa": 550.0,
        "tensile_z_mpa": 500.0,
        "flex_modulus_gpa": 180.0,
        "elongation_pct": 40.0,
        "service_temp_c": 400.0,
        "notes": "Real metal. Expensive. Supports and residual stress matter.",
    },
    "alsi10mg": {
        "id": "alsi10mg",
        "name": "AlSi10Mg (DMLS/SLM)",
        "process_kinds": ["metal_am"],
        "density_g_cm3": 2.67,
        "tensile_xy_mpa": 300.0,
        "tensile_z_mpa": 280.0,
        "flex_modulus_gpa": 70.0,
        "elongation_pct": 8.0,
        "service_temp_c": 150.0,
        "notes": "Light metal AM. Thin overhangs still need supports.",
    },
    "ti64": {
        "id": "ti64",
        "name": "Ti-6Al-4V",
        "process_kinds": ["metal_am"],
        "density_g_cm3": 4.43,
        "tensile_xy_mpa": 900.0,
        "tensile_z_mpa": 850.0,
        "flex_modulus_gpa": 110.0,
        "elongation_pct": 10.0,
        "service_temp_c": 350.0,
        "notes": "Aerospace hammer. Do not pretend an FDM part is this.",
    },
    "al6061": {
        "id": "al6061",
        "name": "Aluminum 6061-T6",
        "process_kinds": ["cnc_mill", "cnc_router", "waterjet", "laser_cut", "sheet_metal"],
        "density_g_cm3": 2.70,
        "tensile_xy_mpa": 310.0,
        "tensile_z_mpa": 310.0,
        "flex_modulus_gpa": 69.0,
        "elongation_pct": 12.0,
        "service_temp_c": 150.0,
        "notes": "Default hobby/protoc CNC metal.",
    },
    "steel1018": {
        "id": "steel1018",
        "name": "Steel 1018",
        "process_kinds": ["cnc_mill", "waterjet"],
        "density_g_cm3": 7.87,
        "tensile_xy_mpa": 440.0,
        "tensile_z_mpa": 440.0,
        "flex_modulus_gpa": 200.0,
        "elongation_pct": 15.0,
        "service_temp_c": 200.0,
        "notes": "Heavy and strong. Slow to mill on small machines.",
    },
    "delrin": {
        "id": "delrin",
        "name": "Delrin (acetal)",
        "process_kinds": ["cnc_mill", "cnc_router"],
        "density_g_cm3": 1.41,
        "tensile_xy_mpa": 70.0,
        "tensile_z_mpa": 70.0,
        "flex_modulus_gpa": 3.0,
        "elongation_pct": 30.0,
        "service_temp_c": 90.0,
        "notes": "Machines beautifully. Good bearing surfaces.",
    },
    "oak": {
        "id": "oak",
        "name": "Oak (along grain)",
        "process_kinds": ["cnc_router", "wood_cut"],
        "density_g_cm3": 0.75,
        "tensile_xy_mpa": 90.0,
        "tensile_z_mpa": 8.0,
        "flex_modulus_gpa": 12.0,
        "elongation_pct": 1.0,
        "service_temp_c": 80.0,
        "notes": "Anisotropic. Across-grain and joints are the weak link, not the coupon strength.",
    },
    "plywood": {
        "id": "plywood",
        "name": "Baltic birch plywood",
        "process_kinds": ["cnc_router", "wood_cut", "laser_cut"],
        "density_g_cm3": 0.70,
        "tensile_xy_mpa": 40.0,
        "tensile_z_mpa": 5.0,
        "flex_modulus_gpa": 10.0,
        "elongation_pct": 1.0,
        "service_temp_c": 80.0,
        "notes": "Sheet good. Cross-laminated; still terrible in peel/Z.",
    },
    "acrylic": {
        "id": "acrylic",
        "name": "Acrylic (PMMA)",
        "process_kinds": ["laser_cut", "cnc_router"],
        "density_g_cm3": 1.18,
        "tensile_xy_mpa": 70.0,
        "tensile_z_mpa": 70.0,
        "flex_modulus_gpa": 3.0,
        "elongation_pct": 4.0,
        "service_temp_c": 70.0,
        "notes": "Lasers well. Brittle around holes and snaps.",
    },
    "pp_im": {
        "id": "pp_im",
        "name": "Polypropylene (injection)",
        "process_kinds": ["injection_mold"],
        "density_g_cm3": 0.91,
        "tensile_xy_mpa": 32.0,
        "tensile_z_mpa": 32.0,
        "flex_modulus_gpa": 1.5,
        "elongation_pct": 100.0,
        "service_temp_c": 90.0,
        "notes": "Living hinges. Needs draft and uniform walls.",
    },
    "abs_im": {
        "id": "abs_im",
        "name": "ABS (injection)",
        "process_kinds": ["injection_mold"],
        "density_g_cm3": 1.04,
        "tensile_xy_mpa": 40.0,
        "tensile_z_mpa": 40.0,
        "flex_modulus_gpa": 2.3,
        "elongation_pct": 20.0,
        "service_temp_c": 85.0,
        "notes": "Common housing plastic. Draft, ribs, uniform walls.",
    },
}

PROCESS_KINDS: dict[str, dict[str, Any]] = {
    "fdm": {
        "id": "fdm",
        "label": "FDM / filament 3D printer",
        "blurb": "Layered plastic. Geometry is free; anisotropy, overhangs, and bed size are not.",
        "params": [
            {"id": "bed_x_mm", "label": "Bed X (mm)", "type": "number", "default": 220},
            {"id": "bed_y_mm", "label": "Bed Y (mm)", "type": "number", "default": 220},
            {"id": "max_z_mm", "label": "Max Z (mm)", "type": "number", "default": 250},
            {"id": "nozzle_mm", "label": "Nozzle (mm)", "type": "number", "default": 0.4},
            {"id": "max_hotend_c", "label": "Max hotend (°C)", "type": "number", "default": 260},
            {"id": "max_bed_c", "label": "Max bed (°C)", "type": "number", "default": 100},
            {"id": "enclosure", "label": "Enclosure", "type": "bool", "default": False},
            {"id": "heated_chamber", "label": "Heated chamber", "type": "bool", "default": False},
            {"id": "hardened_nozzle", "label": "Hardened nozzle", "type": "bool", "default": False},
            {"id": "min_layer_mm", "label": "Min layer (mm)", "type": "number", "default": 0.12},
            {"id": "filament_diameter_mm", "label": "Filament Ø (mm)", "type": "number", "default": 1.75},
        ],
    },
    "sla": {
        "id": "sla",
        "label": "SLA / resin printer",
        "blurb": "Fine detail, weak in impact unless you buy engineering resin. Vat size is the box.",
        "params": [
            {"id": "bed_x_mm", "label": "Vat X (mm)", "type": "number", "default": 218},
            {"id": "bed_y_mm", "label": "Vat Y (mm)", "type": "number", "default": 123},
            {"id": "max_z_mm", "label": "Max Z (mm)", "type": "number", "default": 250},
            {"id": "pixel_um", "label": "XY pixel (µm)", "type": "number", "default": 50},
        ],
    },
    "metal_am": {
        "id": "metal_am",
        "label": "Metal 3D printer (DMLS/SLM/binder)",
        "blurb": "Metal density and strength. Support, powder, and heat-treat constraints still apply.",
        "params": [
            {"id": "bed_x_mm", "label": "Envelope X (mm)", "type": "number", "default": 250},
            {"id": "bed_y_mm", "label": "Envelope Y (mm)", "type": "number", "default": 250},
            {"id": "max_z_mm", "label": "Envelope Z (mm)", "type": "number", "default": 250},
            {"id": "min_feature_mm", "label": "Min feature (mm)", "type": "number", "default": 0.4},
        ],
    },
    "cnc_mill": {
        "id": "cnc_mill",
        "label": "CNC mill",
        "blurb": "Subtractive. Inside corners cannot be sharper than the tool. 3-axis cannot machine undercuts.",
        "params": [
            {"id": "bed_x_mm", "label": "Travel X (mm)", "type": "number", "default": 300},
            {"id": "bed_y_mm", "label": "Travel Y (mm)", "type": "number", "default": 200},
            {"id": "max_z_mm", "label": "Travel Z (mm)", "type": "number", "default": 80},
            {"id": "min_tool_mm", "label": "Smallest tool Ø (mm)", "type": "number", "default": 3.0},
            {"id": "axes", "label": "Axes", "type": "number", "default": 3},
        ],
    },
    "cnc_router": {
        "id": "cnc_router",
        "label": "CNC router",
        "blurb": "Sheet and plate. Great XY, limited Z, large inside radii with typical bits.",
        "params": [
            {"id": "bed_x_mm", "label": "Bed X (mm)", "type": "number", "default": 600},
            {"id": "bed_y_mm", "label": "Bed Y (mm)", "type": "number", "default": 400},
            {"id": "max_z_mm", "label": "Max Z (mm)", "type": "number", "default": 80},
            {"id": "min_tool_mm", "label": "Smallest bit Ø (mm)", "type": "number", "default": 3.175},
        ],
    },
    "wood_cut": {
        "id": "wood_cut",
        "label": "Wood cutting (saw / bandsaw / manual)",
        "blurb": "Mostly prismatic parts from boards and sheet. Compound 3D surfaces are a no.",
        "params": [
            {"id": "bed_x_mm", "label": "Max length (mm)", "type": "number", "default": 1200},
            {"id": "bed_y_mm", "label": "Max width (mm)", "type": "number", "default": 300},
            {"id": "max_z_mm", "label": "Max thickness (mm)", "type": "number", "default": 50},
        ],
    },
    "laser_cut": {
        "id": "laser_cut",
        "label": "Laser cutter",
        "blurb": "2.5D profiles from sheet. If it is not a constant thickness, it is not this process.",
        "params": [
            {"id": "bed_x_mm", "label": "Bed X (mm)", "type": "number", "default": 500},
            {"id": "bed_y_mm", "label": "Bed Y (mm)", "type": "number", "default": 300},
            {"id": "max_z_mm", "label": "Max thickness (mm)", "type": "number", "default": 8},
            {"id": "kerf_mm", "label": "Kerf (mm)", "type": "number", "default": 0.2},
            {"id": "source", "label": "Source", "type": "text", "default": "CO2"},
        ],
    },
    "waterjet": {
        "id": "waterjet",
        "label": "Waterjet",
        "blurb": "2.5D almost any material. Taper and min hole size still exist.",
        "params": [
            {"id": "bed_x_mm", "label": "Bed X (mm)", "type": "number", "default": 600},
            {"id": "bed_y_mm", "label": "Bed Y (mm)", "type": "number", "default": 300},
            {"id": "max_z_mm", "label": "Max thickness (mm)", "type": "number", "default": 50},
            {"id": "min_hole_mm", "label": "Min hole (mm)", "type": "number", "default": 1.0},
        ],
    },
    "injection_mold": {
        "id": "injection_mold",
        "label": "Injection molding",
        "blurb": "Needs draft, uniform walls, and a tool. Undercuts mean slides or they are impossible.",
        "params": [
            {"id": "bed_x_mm", "label": "Max part X (mm)", "type": "number", "default": 200},
            {"id": "bed_y_mm", "label": "Max part Y (mm)", "type": "number", "default": 200},
            {"id": "max_z_mm", "label": "Max part Z (mm)", "type": "number", "default": 80},
            {"id": "min_wall_mm", "label": "Min wall (mm)", "type": "number", "default": 1.2},
            {"id": "draft_deg", "label": "Required draft (°)", "type": "number", "default": 1.5},
        ],
    },
    "sheet_metal": {
        "id": "sheet_metal",
        "label": "Sheet metal (cut + bend)",
        "blurb": "Constant thickness, bend radii, reliefs. It is not a blob.",
        "params": [
            {"id": "bed_x_mm", "label": "Max flat X (mm)", "type": "number", "default": 600},
            {"id": "bed_y_mm", "label": "Max flat Y (mm)", "type": "number", "default": 400},
            {"id": "max_z_mm", "label": "Gauge / thickness (mm)", "type": "number", "default": 3},
            {"id": "min_bend_radius_mm", "label": "Min bend R (mm)", "type": "number", "default": 1.5},
        ],
    },
}

MACHINE_PRESETS: list[dict[str, Any]] = [
    {
        "id": "prusa_mini",
        "kind": "fdm",
        "name": "Prusa Mini+",
        "params": {
            "bed_x_mm": 180,
            "bed_y_mm": 180,
            "max_z_mm": 180,
            "nozzle_mm": 0.4,
            "max_hotend_c": 280,
            "max_bed_c": 100,
            "enclosure": False,
            "heated_chamber": False,
            "hardened_nozzle": False,
        },
        "suggested_materials": ["pla", "petg", "abs"],
    },
    {
        "id": "prusa_mk4",
        "kind": "fdm",
        "name": "Prusa MK4",
        "params": {
            "bed_x_mm": 250,
            "bed_y_mm": 210,
            "max_z_mm": 220,
            "nozzle_mm": 0.4,
            "max_hotend_c": 290,
            "max_bed_c": 120,
            "enclosure": False,
            "heated_chamber": False,
            "hardened_nozzle": False,
        },
        "suggested_materials": ["pla", "petg", "abs", "asa", "nylon"],
    },
    {
        "id": "bambu_p1s",
        "kind": "fdm",
        "name": "Bambu Lab P1S",
        "params": {
            "bed_x_mm": 256,
            "bed_y_mm": 256,
            "max_z_mm": 256,
            "nozzle_mm": 0.4,
            "max_hotend_c": 300,
            "max_bed_c": 100,
            "enclosure": True,
            "heated_chamber": False,
            "hardened_nozzle": False,
        },
        "suggested_materials": ["pla", "petg", "abs", "asa", "petg_cf"],
    },
    {
        "id": "bambu_x1c",
        "kind": "fdm",
        "name": "Bambu Lab X1C",
        "params": {
            "bed_x_mm": 256,
            "bed_y_mm": 256,
            "max_z_mm": 256,
            "nozzle_mm": 0.4,
            "max_hotend_c": 300,
            "max_bed_c": 120,
            "enclosure": True,
            "heated_chamber": False,
            "hardened_nozzle": True,
        },
        "suggested_materials": ["pla", "petg", "abs", "asa", "nylon", "petg_cf", "pa_cf"],
    },
    {
        "id": "ender3",
        "kind": "fdm",
        "name": "Ender 3 / V3",
        "params": {
            "bed_x_mm": 220,
            "bed_y_mm": 220,
            "max_z_mm": 250,
            "nozzle_mm": 0.4,
            "max_hotend_c": 260,
            "max_bed_c": 100,
            "enclosure": False,
            "heated_chamber": False,
            "hardened_nozzle": False,
        },
        "suggested_materials": ["pla", "petg"],
    },
    {
        "id": "voron24_300",
        "kind": "fdm",
        "name": "Voron 2.4 300",
        "params": {
            "bed_x_mm": 300,
            "bed_y_mm": 300,
            "max_z_mm": 300,
            "nozzle_mm": 0.4,
            "max_hotend_c": 300,
            "max_bed_c": 120,
            "enclosure": True,
            "heated_chamber": True,
            "hardened_nozzle": True,
        },
        "suggested_materials": ["pla", "petg", "abs", "asa", "nylon", "pc", "petg_cf", "pa_cf"],
    },
    {
        "id": "elegoo_saturn",
        "kind": "sla",
        "name": "Elegoo Saturn class",
        "params": {"bed_x_mm": 218, "bed_y_mm": 123, "max_z_mm": 250, "pixel_um": 50},
        "suggested_materials": ["sla_standard", "sla_tough"],
    },
    {
        "id": "metal_am_250",
        "kind": "metal_am",
        "name": "Generic metal AM 250 mm",
        "params": {"bed_x_mm": 250, "bed_y_mm": 250, "max_z_mm": 250, "min_feature_mm": 0.4},
        "suggested_materials": ["316l", "alsi10mg", "ti64"],
    },
    {
        "id": "mill_tormach",
        "kind": "cnc_mill",
        "name": "Desktop mill (Tormach / PCNC class)",
        "params": {
            "bed_x_mm": 450,
            "bed_y_mm": 275,
            "max_z_mm": 250,
            "min_tool_mm": 1.5,
            "axes": 3,
        },
        "suggested_materials": ["al6061", "steel1018", "delrin"],
    },
    {
        "id": "mill_mini",
        "kind": "cnc_mill",
        "name": "Mini mill",
        "params": {"bed_x_mm": 200, "bed_y_mm": 100, "max_z_mm": 70, "min_tool_mm": 3.0, "axes": 3},
        "suggested_materials": ["al6061", "delrin"],
    },
    {
        "id": "shapeoko",
        "kind": "cnc_router",
        "name": "Shapeoko / desktop router",
        "params": {"bed_x_mm": 430, "bed_y_mm": 430, "max_z_mm": 80, "min_tool_mm": 3.175},
        "suggested_materials": ["al6061", "delrin", "oak", "plywood", "acrylic"],
    },
    {
        "id": "tablesaw_shop",
        "kind": "wood_cut",
        "name": "Tablesaw / bandsaw shop",
        "params": {"bed_x_mm": 2400, "bed_y_mm": 300, "max_z_mm": 50},
        "suggested_materials": ["oak", "plywood"],
    },
    {
        "id": "glowforge",
        "kind": "laser_cut",
        "name": "Hobby CO2 laser (~500×300)",
        "params": {"bed_x_mm": 500, "bed_y_mm": 300, "max_z_mm": 8, "kerf_mm": 0.2, "source": "CO2"},
        "suggested_materials": ["acrylic", "plywood"],
    },
    {
        "id": "waterjet_generic",
        "kind": "waterjet",
        "name": "Generic waterjet",
        "params": {"bed_x_mm": 600, "bed_y_mm": 300, "max_z_mm": 50, "min_hole_mm": 1.0},
        "suggested_materials": ["al6061", "steel1018", "acrylic"],
    },
    {
        "id": "im_proto",
        "kind": "injection_mold",
        "name": "Prototype injection press",
        "params": {
            "bed_x_mm": 200,
            "bed_y_mm": 200,
            "max_z_mm": 80,
            "min_wall_mm": 1.2,
            "draft_deg": 1.5,
        },
        "suggested_materials": ["pp_im", "abs_im"],
    },
    {
        "id": "sheet_brake",
        "kind": "sheet_metal",
        "name": "Shear + brake",
        "params": {
            "bed_x_mm": 600,
            "bed_y_mm": 400,
            "max_z_mm": 3,
            "min_bend_radius_mm": 1.5,
        },
        "suggested_materials": ["al6061"],
    },
]


def material_by_id(material_id: str) -> dict[str, Any] | None:
    return MATERIALS.get(material_id)


def preset_by_id(preset_id: str) -> dict[str, Any] | None:
    for preset in MACHINE_PRESETS:
        if preset["id"] == preset_id:
            return preset
    return None


def catalog_payload() -> dict[str, Any]:
    from cadfree.cots.catalog import CLASSES, ITEMS, PRICE_NOTE

    parts = [
        {
            "id": item["id"],
            "role": item["role"],
            "name": item["name"],
            "price_usd": item["price_usd"],
            "class_ids": item["class_ids"],
            "envelope_mm": item.get("envelope_mm") or {},
            "mount": item.get("mount") or {},
            "mass_g": item.get("mass_g"),
        }
        for item in ITEMS
    ]
    return {
        "process_kinds": PROCESS_KINDS,
        "machine_presets": MACHINE_PRESETS,
        "materials": MATERIALS,
        "cots_classes": CLASSES,
        "cots_parts": parts,
        "cots_price_note": PRICE_NOTE,
    }
